version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x  # Use the appropriate Python version
      nodejs: 16
    commands:
       # Verify Node.js version to ensure compatibility
      - node -v
      # Install AWS CDK globally
      - npm install -g aws-cdk
      # Verify CDK installation
      - cdk --version
      # Install Python dependencies
      - pip install -r requirements.txt
  build:
    commands:
      # Echo environment variables to verify the environment setup
      - echo "CDK version: $(cdk --version)"
      - echo "Current directory: $(pwd)"
      - echo "Listing files in the directory:"
      - ls -l
      # Run CDK synth to generate the CloudFormation template
      - cdk synth

  post_build:
    commands:
      - echo "Build completed"  # You can add deployment steps here if needed

artifacts:
  files:
    - '**/*'  # Include all files from the current directory
  base-directory: cdk.out  # Upload the CloudFormation templates from the CDK output directory
